version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: demo
      TZ: Asia/Shanghai
    ports:
      - "5432:5432"
    volumes:
      # 数据持久化路径
      - ./data:/var/lib/postgresql/data
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge